DROP TABLE IF EXISTS goals CASCADE;

CREATE TABLE goals (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  image VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  online_goal BOOLEAN NOT NULL DEFAULT FALSE
);
