DROP TABLE IF EXISTS users_goals CASCADE;

CREATE TABLE users_goals (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  goal_id INTEGER REFERENCES goals(id) ON DELETE CASCADE
);
